#!/bin/sh
#
# $NetBSD: mountall,v 1.9 2014/07/22 17:11:09 wiz Exp $
#

# REQUIRE: mountcritremote named ypbind
# PROVIDE: mountall

$_rc_subr_loaded . /etc/rc.subr

name="mountall"
start_cmd="mountall_start"
stop_cmd="mountall_stop"

mountall_start()
{
	echo 'Mounting all file systems...'
	# Mount file systems noted in fstab.
	mount -a
}

mountall_stop()
{
	echo 'Unmounting all file systems...'
	# Unmount file systems noted in fstab.
	umount -a
}

load_rc_config $name
run_rc_command "$1"
