#	$NetBSD: Makefile,v 1.21 2012/11/29 02:05:38 christos Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>
#DBG=-g

PROG=	sysctl
MAN=	sysctl.8

SRCS=	sysctl.c
SRCS+=	${PROG}_hostops.c

.include <bsd.prog.mk>
